name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  node:
    name: Build & Lint (Node ${{ matrix.node }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ['18.x', '20.x']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
  
    - name: 'notify vercel'
       uses: 'vercel/repository-dispatch/actions/status@v1'
        with:
         name: Vercel - game168: สำลี

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (Next.js)
        run: |
          if npm run | grep -q "lint"; then
            npm run lint --if-present
          else
            echo "No lint script found"
          fi

      - name: Build Next.js App
        run: npm run build
